apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tableland-ingress-nginx
spec:
  tls:
    - secretName: tableland-tls-cf-secret
      hosts:
        - staging.tableland.network
  rules:
    - host: staging.tableland.network
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 8080