apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tableland-staging

resources:
- ../base

configMapGenerator:
- envs:
  - configApi.env
  name: configmap-api

patchesStrategicMerge:
- ingress-nginx-patch.yaml